apiVersion: apps/v1
kind: Deployment
metadata:
  name: eksdemo-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: eksdemo-app
  template:
    metadata:
      labels:
        app: eksdemo-app
    spec:
      containers:
      - name: eksdemo-app
        image: IMAGE_PLACEHOLDER
        ports:
        - containerPort: 8080